
def call(def exception) {
    pipelineUtils.choBanner("WE'RE IN THE FAIL SCRIPT: ${exception?.getMessage()} !!!!!!")
}

return this